### PR TITLE
Reactivate import

### PR DESCRIPTION
**Pull request by qdequippe**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by qdequippe** [comment]
It works! ☺️

**Comment by TomasVotruba** [comment]
That is very awesome, I still don't believe it :laughing: :pray: :partying_face: 


Could you remove the old "meetup api" crappy code to keep only useful one? I'll check it then and sunrise the project again :)

**Comment by qdequippe** [comment]
Yes of course, I have to find a way to replace "meetup api" in this command https://github.com/TomasVotruba/friendsofphp.org/blob/main/src/Command/ValidateDeadGroupsCommand.php 🤔 any idea?

**Comment by TomasVotruba** [comment]
I'd crawl the last meetup and use that for checking if group is dead.

**Comment by TomasVotruba** [comment]
Thanks 🙏

**Comment by qdequippe** [comment]
Unfortunately it's not possible, only upcoming meetups are available when crawling publicly 😞

For example this url https://www.meetup.com/groningenphp/events/past/ is protected ...

**Comment by qdequippe** [comment]
I can check the latest meetup available in the meetups json?

**Comment by TomasVotruba** [comment]
> For example this url [meetup.com/groningenphp/events/past](https://www.meetup.com/groningenphp/events/past/) is protected ...

I see, in that case don't worry about it. We can drop it :+1:

> I can check the latest meetup available in the meetups json?

Not really, there are only active meetups from the future.

**Pull request merged**
