### PR TITLE
Revert sunset

### PR DESCRIPTION
**Pull request by qdequippe**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you :clap:

**Comment by qdequippe** [comment]
You're welcome ☺️

**Comment by TomasVotruba** [comment]
:+1: 

Btw, it seems some meetups are missing.

E.g. this is coming in January 19th in Amsterdam, but is not on the map. Any idea what is wrong,
https://www.meetup.com/amsterdamphp/events/tfqnzsyfccbzb/

**Comment by TomasVotruba** [comment]
Once more thanks for the update!

Few weeks later, I still feel I want to pass on this project and focus on something else.

I'll probably tweet it and give away for public, but wanted to give you prirority queue as you made everything works basically :) 

<br>

This is current traffic:

image

<br>

* The domain expires on: 2024-06-02
* I can transfer it to your registrar.

Would you be interested in that?

**Comment by qdequippe** [comment]
> 👍
> 
> Btw, it seems some meetups are missing.
> 
> E.g. this is coming in January 19th in Amsterdam, but is not on the map. Any idea what is wrong? https://www.meetup.com/amsterdamphp/events/tfqnzsyfccbzb/

I found why, I will fix it.

> Would you be interested in that?
it would be a great honor :)

**Comment by TomasVotruba** [comment]
That's perfect :)

Let's start with moving the repository.
Then domain - send mail here: [tomas.vot@gmail.com](mailto:tomas.vot@gmail.com)

**Comment by TomasVotruba** [comment]
So the repository cannot be removed, untill you remove your fork. Could you handle it?

**Comment by qdequippe** [comment]
> So the repository cannot be removed, untill you remove your fork. Could you handle it?

Done ✅

**Pull request merged**
